### ISSUE TITLE
F-252 Falla al generar listado extracompleto de casos con algunos casos (reportado por Juana)

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sivel2_sjrcol#252]

**Comment by vtamara** [comment]
Se mueve bitacora para dejar una en blanco. Se genera el reporte completo el 25.Mar a las 4:29.   
La generación continúa a las 4:44 sin reporte de error.
Generación continúa a las 5:26 sin reporte de error.
Generación continúa a las 9:10 sin reporte de error.
Generación se detuvo a las 12:30AM.
Examinando la bitácora se encontró un error que no había sido reportado, se logro reproducir: https://github.com/pasosdeJesus/sivel2_sjrcol/issues/274

Examinando más la bitácora se ve que logra completarse primera parte de generación para 12893 casos, que parece la totalidad de los casos para el momento de la prueba.  Por lo visto se generaron de manera consecutiva hasta el código 17341.

El 30.Mar. sólo para descartar se generan 130 casos con fecha igual o posterior a la del 17341.  El reporte se genera con exito e incluye el caso 17341.

Parece que la generación del más completo se detuvo por algún tiempo excedido.

Para experimentar el 31.Mar se generan 1064 casos más recientes con fecha de desp a partir del 1.Nov.2020.     Se generó sin problemas. 


Sería bueno reservar tiempo para hacer más pruebas.

**Comment by vtamara** [comment]
Tras un segundo reporte de la falla al generar un reporte de 802 casos, se encuentra en servidor un volcado de núcleo de soffice.  Se analiza:
```
 % ls -l soffice.bin.core 
-rw-------  1 X X  45263776 Apr  5 21:25 soffice.bin.core

% gdb /usr/local/lib/libreoffice/program/soffice.bin soffice.bin.core
...
(gdb) bt                                                                        
#0  thrkill () at -:3                   
#1  0x000002271b66789e in _libc_abort ()                                        
    at /usr/src/lib/libc/stdlib/abort.c:51  
#2  0x000002271b652cd6 in wrterror (d=Variable "d" is not available.            
)                                                                               
    at /usr/src/lib/libc/stdlib/malloc.c:300                                    
#3  0x000002271b65606a in find_chunknum (d=Variable "d" is not available.       
)                                                                               
    at /usr/src/lib/libc/stdlib/malloc.c:1070                                   
#4  0x000002271b6532b4 in ofree (argpool=0x7f7ffffbd200, p=0x22778684140,       
    clear=0, check=Variable "check" is not available.                           
) at /usr/src/lib/libc/stdlib/malloc.c:1431                                                                                                                     
#5  0x000002271b652f20 in free (ptr=0x22778684140)                              
    at /usr/src/lib/libc/stdlib/malloc.c:1488                                                                                                                   
#6  0x000002271b66c08d in _libc___cxa_finalize (dso=Variable "dso" is not available.
)                                                                                                                                                               
    at /usr/src/lib/libc/stdlib/atexit.c:177                                    
#7  0x000002271b694991 in _libc_exit (status=0)                                 
    at /usr/src/lib/libc/stdlib/exit.c:54                                       
#8  0x000002250caff142 in ___start ()   
   from /usr/local/lib/libreoffice/program/soffice.bin                          
#9  0x0000000000000000 in ?? ()         
Current language:  auto; currently asm                                          
(gdb)                                                 
```

Esta falla con `malloc` nos hace pensar que se trató de un agotamiento de memoría durante la conversión de la hoja de cálculo a XLSX.

**Comment by vtamara** [comment]
Por su estandarización inicial como estandares abiertos, estamos convirtiendo a ODS y mediante libreoffice conviritiendo este a XLSX cuando se requiere.  Podríamos experimentar conversión directa a XLSX con alguna librería con ese fin.
